# Generated by Django 6.0.3 on 2026-03-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_phoneotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
