# Generated by Django 6.0.2 on 2026-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_driver_license_image_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
