# Generated by Django 6.0.2 on 2026-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_driver_license_expiry_driver_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
    ]
