# Generated by Django 6.0.2 on 2026-03-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0010_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
