# Generated by Django 6.0.3 on 2026-03-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0012_carbrand_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='car_logos/'),
        ),
    ]
