# Generated by Django 6.0.3 on 2026-03-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0017_customer_profile_picture_driver_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='selected_vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('cargo', 'Cargo / Goods Vehicle')], default='car', max_length=10),
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='load_capacity',
            field=models.FloatField(blank=True, help_text='Load capacity in kg (for cargo vehicles)', null=True),
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('cargo', 'Cargo / Goods Vehicle')], default='car', max_length=10),
        ),
    ]
