# Generated by Django 6.0.3 on 2026-03-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0018_ride_selected_vehicle_type_uservehicle_load_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('cargo', 'Cargo / Goods Vehicle')], default='car', max_length=10),
        ),
    ]
