# Generated by Django 6.0.3 on 2026-03-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0019_driver_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
