# Generated by Django 6.0.3 on 2026-03-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0020_customer_is_online_driver_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
