# Generated by Django 6.0.3 on 2026-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0022_driver_total_earnings_ride_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
