# Generated by Django 6.0.3 on 2026-03-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0023_ride_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
