# Generated by Django 6.0.3 on 2026-03-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0025_alter_emailotp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.CreateModel(
            name='LicenseVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('govt_name', models.CharField(blank=True, max_length=200)),
                ('govt_dob', models.CharField(blank=True, max_length=20)),
                ('govt_license_type', models.CharField(blank=True, max_length=100)),
                ('govt_expiry', models.CharField(blank=True, max_length=20)),
                ('govt_address', models.TextField(blank=True)),
                ('govt_raw_response', models.JSONField(blank=True, default=dict)),
                ('mismatches', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_verification', to='ride.driver')),
            ],
        ),
    ]
