# Generated by Django 6.0.3 on 2026-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0026_driver_date_of_birth_driver_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='drop_location',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='price',
            new_name='estimated_fare',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='selected_vehicle_type',
            new_name='vehicle_type',
        ),
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/back/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/drivers/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=20),
        ),
    ]
