# Generated by Django 6.0.3 on 2026-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0027_rename_drop_location_ride_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_pickup_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='waiting_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
