# Generated by Django 6.0.3 on 2026-03-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0029_ride_base_fare_ride_extra_charge_ride_extra_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('searching', 'Searching'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=20),
        ),
    ]
