# Generated by Django 6.0.3 on 2026-03-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0030_ride_scheduled_time_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_daily_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='waiting_time',
            field=models.IntegerField(default=0),
        ),
    ]
