# Generated by Django 6.0.3 on 2026-03-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0031_ride_is_daily_package_ride_total_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='surge_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
