# Generated by Django 6.0.3 on 2026-03-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0032_driver_current_lat_driver_current_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
