# Generated by Django 6.0.3 on 2026-03-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0033_customer_full_name_driver_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservehicle',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
