# Generated by Django 6.0.3 on 2026-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0035_driverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='upi_id',
            field=models.CharField(blank=True, help_text="Driver's UPI ID for direct payments", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('searching', 'Searching'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='searching', max_length=20),
        ),
        migrations.DeleteModel(
            name='DriverLocation',
        ),
    ]
