# Generated by Django 6.0.2 on 2026-04-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0036_driver_upi_id_alter_ride_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
