# Generated by Django 6.0.3 on 2026-04-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0037_driver_vehicle_model_driver_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cargo_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='load_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='load_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='night_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
