# Generated by Django 6.0.3 on 2026-04-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0038_ride_cargo_capacity_ride_load_charge_ride_load_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
