# Generated by Django 6.0.2 on 2026-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0039_ride_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
