# Generated by Django 6.0.2 on 2026-04-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0040_driver_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('commission_percentage', models.FloatField(default=8.0)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.AlterField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
