# Generated by Django 6.0.3 on 2026-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0042_driver_total_commission_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
